package com.example.todo.todo;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.Instant;
import java.time.LocalDate;

/**
 * A single todo item.
 *
 * <p>This is the console demo's "domain object". When you evaluate
 * {@code todoService.findAll()} in the REPL, the console derives a table from
 * exactly these properties ({@code id}, {@code title}, {@code description},
 * {@code completed}, {@code createdAt}, {@code completedAt}, {@code dueDate},
 * {@code overdue}) using the public getters below — no console-specific code
 * exists in this class.
 */
@Entity
@Table(name = "todos")
public class Todo {

    /** Surrogate key, generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Short summary shown in the list. Required, at most 200 characters. */
    @Column(nullable = false, length = 200)
    private String title;

    /** Optional longer text. At most 2000 characters. */
    @Column(length = 2000)
    private String description;

    /** Whether the item is done. Kept in sync with {@link #completedAt}. */
    @Column(nullable = false)
    private boolean completed = false;

    /** Creation timestamp, set once by {@link #onCreate()}. */
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /** When the item was completed, or {@code null} while it is active. */
    private Instant completedAt;

    /**
     * Optional deadline. Drives {@link #isOverdue()} and the repository's
     * "overdue" query.
     */
    private LocalDate dueDate;

    /** Required by JPA; not for application code. */
    protected Todo() {
        // for JPA
    }

    /**
     * Creates a new todo.
     *
     * @param title       required, already validated by {@code TodoRequest}
     * @param description optional free text
     * @param dueDate     optional deadline
     */
    public Todo(String title, String description, LocalDate dueDate) {
        this.title = title;
        this.description = description;
        this.dueDate = dueDate;
    }

    /** JPA lifecycle hook: stamp {@link #createdAt} on first insert. */
    @PrePersist
    void onCreate() {
        if (createdAt == null) {
            createdAt = Instant.now();
        }
    }

    /**
     * Marks the todo as done/undone, tracking when it was completed.
     *
     * <p>Maintaining {@code completedAt} here (rather than in the service)
     * keeps the invariant local to the entity, which is what makes
     * {@code todoService.toggle(id)} a one-liner.
     */
    public void setCompleted(boolean completed) {
        this.completed = completed;
        this.completedAt = completed ? Instant.now() : null;
    }

    /**
     * Computed: an active item whose due date is in the past. Not persisted,
     * but exposed as the {@code overdue} property in the REST response and in
     * the console's rendered table.
     */
    public boolean isOverdue() {
        return !completed && dueDate != null && dueDate.isBefore(LocalDate.now());
    }

    public Long getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isCompleted() {
        return completed;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getCompletedAt() {
        return completedAt;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    @Override
    public String toString() {
        return "Todo{id=%d, title='%s', completed=%s}".formatted(id, title, completed);
    }
}
